
{
    'name': 'sale practice model ',
    'version': '1.0.0',
    'description': """""sale model pratice""",
    'depends': ['base','sale_management','sale','stock'],
     "data" : ["security/ir.model.access.csv",
              "views/menu.xml",
              "wizard/practice_wizard.xml",
              "wizard/sale_wizard.xml",
              "views/menu_inherit.xml",
              "views/commission.xml",
              "views/commission_online.xml",
              "views/practice_view.xml",
              "views/sale.xml",
              "reports/practice.xml",
    ],
    'demo': [],
    'installable': True,
    'auto_install' : False,
    'license': 'LGPL-3',
     'sequence' : -500,
}